In [1]:
import numpy as np
import pandas as pd
from random import sample
from datetime import datetime, timedelta

In [2]:
def geramatriz():
  aux = sample(range(0, 9), 9)
  matriz = np.array([aux[i:i + 3] for i in range(0, len(aux), 3)])
  return matriz

def findzeros(m):
  vetor = []
  for i in range(3):
      for j in range(3):
        if m[i][j]==0:
          vetor=[i,j]
  return vetor

def m_exists(m1, m2):
  for matriz in m1:
    result = (matriz == m2)
    if(result.all()==True):
      return 1
  return 0


## Funções:
geramatriz: Gera uma matriz 3x3 aleatoriamente com numeros de 0 a 9

findzeros: acha o par ordenado o qual está o 0 da matriz (posição "vazia")

m_exists: verifica se uma matriz já está na lista de matrizes geradas

In [3]:
def game(m, arvore, backup, tam, ini, end):
  final = np.array([[1,2,3], [4,5,6], [7,8,0]])  #matriz objetivo
  matriz = m.copy()
  v = []
  finish = (matriz == final)
  v=findzeros(matriz)  #acha o ponto livre da matriz

  if v == [0,0]:  ##cada if verifica onde está o zero, e então gera as matrizes com os possíveis movimentos
    m1 = matriz.copy()
    m1[0][0]=matriz[0][1]
    m1[0][1]=matriz[0][0]
    block = m_exists(backup,m1)  #verifica se a matriz já está na lista de matrizes geradas (backup)
                                 #se não está, adiciona na lista árvore (matrizes a serem analisadas)
                                 #e na backup (armazena matrizes já geradas)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[0][0]=matriz[1][0]
    m2[1][0]=matriz[0][0]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)
  elif v == [0,1]:
    m1 = matriz.copy()
    m1[0][1]=matriz[0][0]
    m1[0][0]=matriz[0][1]
    block = m_exists(backup,m1)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[0][1]=matriz[0][2]
    m2[0][2]=matriz[0][1]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)
    m3 = matriz.copy()
    m3[0][1]=matriz[1][1]
    m3[1][1]=matriz[0][1]
    block = m_exists(backup,m3)
    if block ==0:
      arvore.append(m3)
      backup.append(m3)
  elif v == [0,2]:
    m1 = matriz.copy()
    m1[0][2]=matriz[0][1]
    m1[0][1]=matriz[0][2]
    block = m_exists(backup,m1)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[0][2]=matriz[1][2]
    m2[1][2]=matriz[0][2]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)
  elif v == [1,0]:
    m1 = matriz.copy()
    m1[1][0]=matriz[0][0]
    m1[0][0]=matriz[1][0]
    block = m_exists(backup,m1)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[1][0]=matriz[1][1]
    m2[1][1]=matriz[1][0]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)
    m3 = matriz.copy()
    m3[1][0]=matriz[2][0]
    m3[2][0]=matriz[1][0]
    block = m_exists(backup,m3)
    if block ==0:
      arvore.append(m3)
      backup.append(m3)
  elif v == [1,1]:
    m1 = matriz.copy()
    m1[1][1]=matriz[0][1]
    m1[0][1]=matriz[1][1]
    block = m_exists(backup,m1)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[1][1]=matriz[2][1]
    m2[2][1]=matriz[1][1]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)
    m3 = matriz.copy()
    m3[1][1]=matriz[1][0]
    m3[1][0]=matriz[1][1]
    block = m_exists(backup,m3)
    if block ==0:
      arvore.append(m3)
      backup.append(m3)
    m4 = matriz.copy()
    m4[1][1]=matriz[1][2]
    m4[1][2]=matriz[1][1]
    block = m_exists(backup,m4)
    if block ==0:
      arvore.append(m4)
      backup.append(m4)
  elif v == [1,2]:
    m1 = matriz.copy()
    m1[1][2]=matriz[0][1]
    m1[0][1]=matriz[1][2]
    block = m_exists(backup,m1)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[1][2]=matriz[1][1]
    m2[1][1]=matriz[1][2]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)
    m3 = matriz.copy()
    m3[1][2]=matriz[2][2]
    m3[2][2]=matriz[1][2]
    block = m_exists(backup,m3)
    if block ==0:
      arvore.append(m3)
      backup.append(m3)
  elif v == [2,0]:
    m1 = matriz.copy()
    m1[2][0]=matriz[1][0]
    m1[1][0]=matriz[2][0]
    block = m_exists(backup,m1)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[2][0]=matriz[2][1]
    m2[2][1]=matriz[2][0]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)
  elif v == [2,1]:
    m1 = matriz.copy()
    m1[2][1]=matriz[2][0]
    m1[2][0]=matriz[2][1]
    block = m_exists(backup,m1)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[2][1]=matriz[1][1]
    m2[1][1]=matriz[2][1]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)
    m3 = matriz.copy()
    m3[2][1]=matriz[2][2]
    m3[2][2]=matriz[2][1]
    block = m_exists(backup,m3)
    if block ==0:
      arvore.append(m3)
      backup.append(m3)
  elif v == [2,2]:
    m1 = matriz.copy()
    m1[2][2]=matriz[1][2]
    m1[1][2]=matriz[2][2]
    block = m_exists(backup,m1)
    if block ==0:
      arvore.append(m1)
      backup.append(m1)
    m2 = matriz.copy()
    m2[2][2]=matriz[2][1]
    m2[2][1]=matriz[2][2]
    block = m_exists(backup,m2)
    if block ==0:
      arvore.append(m2)
      backup.append(m2)

  aux = arvore[0]  #variavel auxiliar que receberá a primeira matriz da fila de matrizes
  arvore.pop(0)  #matriz é excluida da lista de matrizes a serem analisadas
  finish = (aux == final)  #verifica se a matriz atual é a matriz target
  if(finish.all() == True):  #caso a matriz atual seja igual a matriz target, printa a hora de inicio/fim, e a quantidade de matrizes percorridas
    print('Inicio')
    print(ini)
    print('Fim')
    end = (str(datetime.now()))
    print(end)
    print(f'Tamanho = {tam}')
    return{'Fim'+end}
  elif(finish.all() == False):  #caso a matriz atual seja diferente da matriz target
    tam = tam+1  #incrementa o contador de matrizes percorridas
    game(aux,arvore, backup, tam, ini, end)  #chama recursivamente a função

In [5]:
import sys
sys.setrecursionlimit(100000000)

Aumenta o limite de recursão, para não parar por estoura-lo

Abaixo, são criadas matrizes manualmente para mostrar o código executando em um tempo menor

In [7]:

tam=0
mm = np.array([[1,2,3], [4,6,8], [7,0,5]])
mm1 = np.array([[1,2,3], [4,0,6], [7,5,8]])
mm2 = np.array([[1,2,3], [4,6,8], [7,5,0]])
mm3 = np.array([[1,2,3], [4,0,8], [7,6,5]])
mm4 = np.array([[1,0,3], [4,2,8], [7,6,5]])
mm5 = np.array([[1,0,3], [4,8,2], [7,6,5]])
mm6 = np.array([[4,1,3], [0,8,2], [7,6,5]])
mm7 = np.array([[4,1,3], [7,8,2], [0,6,5]])
mm8 = np.array([[4,1,3], [7,8,2], [6,0,5]])

In [8]:
end = datetime.now()
arvore0 = []
backup0 = []
tam=0
game(mm, arvore0, backup0, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:28:00.506748
Fim
2023-03-20 19:28:00.539760
Tamanho = 69


In [9]:
end = datetime.now()
arvore1 = []
backup1 = []
tam=0
game(mm1, arvore1, backup1, tam, ini = datetime.now(), end=end)


Inicio
2023-03-20 19:28:02.703886
Fim
2023-03-20 19:28:02.704881
Tamanho = 8


In [11]:
tam=0
end = datetime.now()
arvore2 = []
backup2 = []
game(mm2, arvore2, backup2, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:28:24.006905
Fim
2023-03-20 19:28:24.011904
Tamanho = 25


In [12]:
end = datetime.now()
arvore3 = []
backup3 = []
tam=0
game(mm3, arvore3, backup3, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:28:25.833324
Fim
2023-03-20 19:28:25.926345
Tamanho = 122


In [13]:
end = datetime.now()
arvore4 = []
backup4 = []
tam=0
game(mm4, arvore4, backup4, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:28:28.124453
Fim
2023-03-20 19:28:28.389257
Tamanho = 203


In [14]:
end = datetime.now()
arvore5 = []
backup5 = []
tam=0
game(mm5, arvore5, backup5, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:28:30.308347
Fim
2023-03-20 19:28:34.681481
Tamanho = 848


In [15]:
end = datetime.now()
arvore6 = []
backup6 = []
tam=0
game(mm6, arvore6, backup6, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:28:34.715889
Fim
2023-03-20 19:28:59.871513
Tamanho = 2027


In [16]:
end = datetime.now()
arvore7 = []
backup7 = []
tam=0
game(mm7, arvore7, backup7, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:28:59.901192
Fim
2023-03-20 19:29:54.278642
Tamanho = 2961


In [17]:
end = datetime.now()
arvore8 = []
backup8 = []
tam=0
game(mm8, arvore8, backup8, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:29:54.351704
Fim
2023-03-20 19:33:12.543951
Tamanho = 5683


In [18]:
m = geramatriz()
m
print(m)

[[2 4 5]
 [8 0 1]
 [6 7 3]]


In [19]:
arvore = []
end = datetime.now()
backup = []
tam=0
game(m, arvore, backup, tam, ini = datetime.now(), end=end)

Inicio
2023-03-20 19:33:25.096520
Fim
2023-03-21 03:35:50.519161
Tamanho = 74046


Este ultimo foi gerado pela função, para ver o tempo de achar uma solução de uma matriz realmente aleatoria